export const ARTICLES_FETCHED = 'ARTICLES_FETCHED';
export const ARTICLE_FETCHED = 'ARTICLE_FETCHED';
export const ARTICLE_SUBSCRIBE = 'ARTICLE_SUBSCRIBE'

export const EVENTS_FETCHED = 'EVENTS_FETCHED';
export const EVENT_FETCHED = 'EVENT_FETCHED';

export const COMMUNITIES_FETCHED = 'COMMUNITIES_FETCHED';
export const COMMUNITY_FETCHED = 'COMMUNITY_FETCHED';

export const PROGRAMS_FETCHED = 'PROGRAMS_FETCHED';

export const COMMENTS_FETCHED = 'COMMENTS_FETCHED';
export const COMMENT_ADD = 'COMMENT_ADD';
export const COMMENT_UPDATE = 'COMMENT_UPDATE';
export const COMMENT_DELETE = 'COMMENT_DELETE';

export const MEMBERS_FETCHED = 'MEMBERS_FETCHED';

export const REGISTRATION = 'REGISTRATION';
export const SIGN_IN = 'SIGN_IN';
export const GET_PROFILE_INFO = 'GET_PROFILE_INFO';
export const GET_USER_RULES = 'GET_USER_RULES';
export const ADD_TOKEN = 'ADD_TOKEN';

export const SHOW_PROFILE_MODAL = 'SHOW_PROFILE_MODAL';
export const ALERT_PROFILE_MODAL = 'ALERT_PROFILE_MODAL';
export const SHOW_PROFILE_PHONE_MODAL = 'SHOW_PROFILE_PHONE_MODAL';
export const SET_NEED_CALLBACK = 'SET_NEED_CALLBACK'

export const NAVIGATOR_VISIBLE_TOGGLE = 'NAVIGATOR_VISIBLE_TOGGLE';
export const NAV_VISIBLE_TOGGLE = 'NAV_VISIBLE_TOGGLE';
export const FETCHED_SIDEBAR_ITEMS = 'FETCHED_SIDEBAR_ITEMS';
export const SET_SIDEBAR_TYPE = 'SET_SIDEBAR_TYPE';

export const LEFT_MENU_STATE = 'LEFT_MENU_STATE';
export const GET_USER_INFO = 'GET_USER_INFO';
export const LOGOUT_USER = 'LOGOUT_USER';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';

export const SCHOOLS_FETCHED = 'SCHOOLS_FETCHED';
export const SCHOOL_FETCHED = 'SCHOOL_FETCHED';
export const CONNECTED_COURSES_FETCHED = 'CONNECTED_COURSES_FETCHED';
export const CONNECTED_COMMUNITIES_FETCHED = 'CONNECTED_COMMUNITIES_FETCHED';

export const COURSES_FETCHED = 'COURSES_FETCHED';
export const COURSE_FETCHED = 'COURSE_FETCHED';

export const FETCH_LESSONS = 'FETCH_LESSONS';
export const ADD_LESSON = 'ADD_LESSON';
export const UPDATE_LESSON = 'UPDATE_LESSON';
export const DELETE_LESSON = 'DELETE_LESSON';

export const FETCH_SERVICES_LIST = 'FETCH_SERVICES_LIST';
export const FETCH_SERVICE = 'FETCH_SERVICE';
export const FETCH_SERVICE_RATES = 'FETCH_SERVICE_RATES';

export const CLUSTERS_FETCHED = 'CLUSTERS_FETCHED';
export const CLUSTER_FETCHED = 'CLUSTER_FETCHED';

/**
 * Notifications
 */
export const NOTIFICATION_FETCHED = 'NOTIFICATION_FETCHED'
export const NOTIFICATION_ADD = 'NOTIFICATION_ADD'
export const NOTIFICATION_VIEW = 'NOTIFICATION_VIEW'

export const FETCH_PEOPLE_PROJECTS = 'FETCH_PEOPLE_PROJECTS';
export const FETCH_PEOPLE_PROJECT = 'FETCH_PEOPLE_PROJECT';
export const FETCH_PROJECTS = 'FETCH_PROJECTS';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const FETCH_PROJECT = 'FETCH_PROJECT';
export const FETCH_USER_PROJECTS = 'FETCH_USER_PROJECTS';
export const ADD_PROJECT = 'ADD_PROJECT';
export const PROJECT_UPDATE = 'PROJECT_UPDATE';
export const EDIT_PROJECT = 'EDIT_PROJECT';
export const FETCH_USER_INFO = 'FETCH_USER_INFO';
export const FETCH_PROJECT_POST = 'FETCH_PROJECT_POST'
export const FETCH_PROJECT_STATISTICS = 'FETCH_PROJECT_STATISTICS';
export const SHOW_ARTICLE_FORM = 'SHOW_ARTICLE_FORM'

